### PR TITLE
uploaded the project

### PR DESCRIPTION
**Pull request by frank2ny**

### CODE REVIEW

**Review by BenMaruchu — COMMENTED** [review]
Hello @frank2ny 

Nice Work.

I have a question did you commit via git or you uploaded these files?

**Comment by frank2ny** [comment]
@BenMaruchu 
NO , i used Git console.
created a repo. on Github and clone it.
created a branch "feture-ui" and ''develop'
checkout to feature-ui branch and push all the code while on "feature-ui" branch

**Comment by frank2ny** [comment]
@BenMaruchu 
should i merge the pull request now?? ... or whats the next move .

**Comment by BenMaruchu** [comment]
So you created a single commit only?

We will merge once the PR is approved

**Comment by frank2ny** [comment]
@BenMaruchu 
yes , because i did all the project offline and push all at once to the feature-ui branch

**Comment by BenMaruchu** [comment]
@frank2ny Ok ... So one thing you need to improve .. always commit often and small changes which will be easier for someone to review your codes

Also if your are using vscode as your editor you can configure it to format your code on save so that they will have consistency in arrangement..

Otherwise good work .. but remember to commit often small changes.

**Review by BenMaruchu — APPROVED** [review]

**Comment by frank2ny** [comment]
@BenMaruchu 
yes , thats true, will correct that mistake. 
thanks

**Pull request merged**
